[module]
module.name = "Numbers\Users\Chats"
module.code = "C5"
module.title = "C/5 Chats"
module.version = "1.0.0"

[dependencies]
dep.submodule.Numbers.Backend.Db.__any = 1
dep.submodule.Numbers.Tenants.Tenants = 1
dep.submodule.Numbers.Users.Users = 1
dep.submodule.Numbers.Internalization.Internalization = 1
dep.submodule.Numbers.AI.SDK = 1

; --- models (name and parent class) ---
dep.model.\Numbers\Users\Chats\Model\Groups = "\Object\Table"
dep.model.\Numbers\Users\Chats\Model\Channels = "\Object\Table"
dep.model.\Numbers\Users\Chats\Model\Chats = "\Object\Table"
dep.model.\Numbers\Users\Chats\Model\Chat\Users = "\Object\Table"
dep.model.\Numbers\Users\Chats\Model\Chat\Sessions = "\Object\Table"
dep.model.\Numbers\Users\Chats\Model\Chat\Messages = "\Object\Table"
dep.model.\Numbers\Users\Chats\Model\Chat\Message\Reads = "\Object\Table"
dep.model.\Numbers\Users\Chats\Model\Chat\Message\Reactions = "\Object\Table"
dep.model.\Numbers\Users\Chats\Model\Chat\Invites = "\Object\Table"
dep.model.\Numbers\Users\Chats\Model\Chat\User\ThreadUnreads = "\Object\Table"
dep.model.\Numbers\Users\Chats\Model\Group\Map = "\Object\Table"
dep.model.\Numbers\Users\Chats\Model\Group\Users = "\Object\Table"
dep.model.\Numbers\Users\Chats\Model\Group\Channels = "\Object\Table"
dep.model.\Numbers\Users\Chats\Model\Canvases = "\Object\Table"
dep.model.\Numbers\Users\Chats\Model\Canvas\Map = "\Object\Table"
dep.model.\Numbers\Users\Chats\Model\Canvas\Lists = "\Object\Table"
dep.model.\Numbers\Users\Chats\Model\Canvas\List2\Users = "\Object\Table"

; data
dep.model.\Numbers\Users\Chats\Model\Chat\ChatTypes = "\Object\Data"
dep.model.\Numbers\Users\Chats\Model\Chat\ChatStartTypes = "\Object\Data"
dep.model.\Numbers\Users\Chats\Model\Chat\ChatDMTypes = "\Object\Data"
dep.model.\Numbers\Users\Chats\Model\Chat\ChatChannelTypes = "\Object\Data"
dep.model.\Numbers\Users\Chats\Model\Channel\InviteStatuses = "\Object\Data"
dep.model.\Numbers\Users\Chats\Model\Canvas\CanvasTypes = "\Object\Data"

; imports
dep.model.\Numbers\Users\Chats\Data\Import = "\Object\Import"
dep.model.\Numbers\Users\Chats\Data\System = "\Object\Import"
dep.model.\Numbers\Users\Chats\Data\System2 = "\Object\Import"
dep.model.\Numbers\Users\Chats\Data\QuickActions = "\Object\Import"
dep.model.\Numbers\Users\Chats\Data\Batches = "\Object\Import"

; APIs
dep.api.\Numbers\Users\Chats\API\V1\C5\ChatMessages = "API"

; localizations
dep.loc.\Numbers\Users\Chats\Localization\Messages = "Other"

[help]
; C/5 Chats
