[*,production,staging,testing,development]
flag.global.default_postlogin_page = "/Numbers/Users/Users/Controller/Helper/Dashboard"
flag.global.default_login_page = "/Numbers/Users/Users/Controller/Login"
flag.global.default_logout_page = "/Numbers/Users/Users/Controller/Logout"
flag.global.default_mfa_page = "/Numbers/Users/Users/Controller/MFA"

; --- U/M Form ---
flag.form.um_users.unique_numeric_phone = true

; --- scopes ---
scope.UM.Register.um_role_code = "DEFAULT"
scope.UM.Register.on_organization_code = "DEFAULT"
scope.UM.Register.um_user_type_id = 10

; --- scoped attributes ---
scoped_attributes.subform.list = "\Numbers\Users\Users\Form\ABAC\List2\AssignmentRecordsList2"
scoped_attributes.subform.link = "um_abac_assignment_records_list"

; --- import presets ---
import_presets.import_form.available = "\Numbers\Users\Users\Helper\Import\Presets::seeAvailableImports"

; --- registrations ---
registration.UM.Users.name = "Register (Advanced)"
registration.UM.Users.icon = "fas fa-chess-board"
registration.UM.Users.link = "host://Numbers/Users/Users/Controller/Register/_Index"
registration.UM.Users.scope = "UM.Register"
registration.UM.Users.hold = true
registration.UM.Users.channel = "Website (Advanced)"

registration.UM.UserSimple.name = "Register (Simple)"
registration.UM.UserSimple.icon = "fas fa-chess-board"
registration.UM.UserSimple.link = "host://Numbers/Users/Users/Controller/Register/_Simple"
registration.UM.UserSimple.scope = "UM.Register"
registration.UM.UserSimple.hold = false
registration.UM.UserSimple.channel = "Website (Simple)"

; --- quick search and mentions ---
qsm.UM.Users.um_user_id.column_key="um_user_id"
qsm.UM.Users.um_user_id.column_id="um_user_id"
qsm.UM.Users.um_user_id.column_id_numeric = true
qsm.UM.Users.um_user_id.column_name="um_user_name"
qsm.UM.Users.um_user_id.column_orderby="um_user_name"
qsm.UM.Users.um_user_id.name="User ID"
qsm.UM.Users.um_user_id.description="U/M Users"
qsm.UM.Users.um_user_id.loc="NF.Form.UserSpaceID"
qsm.UM.Users.um_user_id.marker="~"
qsm.UM.Users.um_user_id.model="\Numbers\Users\Users\Model\Users"
qsm.UM.Users.um_user_id.have_batches = true
qsm.UM.Users.um_user_id.role = "context_user"

qsm.UM.Users.um_user_code.column_key="um_user_code"
qsm.UM.Users.um_user_code.column_id="um_user_id"
qsm.UM.Users.um_user_code.column_id_numeric = true
qsm.UM.Users.um_user_code.column_name="um_user_name"
qsm.UM.Users.um_user_code.column_orderby="um_user_name"
qsm.UM.Users.um_user_code.name="User Code"
qsm.UM.Users.um_user_code.loc="NF.Form.UserCode"
qsm.UM.Users.um_user_code.description="U/M Users"
qsm.UM.Users.um_user_code.marker="~"
qsm.UM.Users.um_user_code.model="\Numbers\Users\Users\Model\Users"
qsm.UM.Users.um_user_code.have_batches = true
qsm.UM.Users.um_user_code.role = "context_user"

; --- commands and mentions ---
qsc.UM.Users.date.name = "Date"
qsc.UM.Users.date.loc = "NF.Form.Date"
qsc.UM.Users.date.marker = "`"
qsc.UM.Users.date.command = "`date"
qsc.UM.Users.date.model = "\Numbers\Users\Users\Helper\DateCommands::date"
