[*,production,staging,testing,development]

chat.assistant.code = "AI_ASSISTANT"
chat.assistant.role = "assistant"

; --- quick search and mentions ---
qsm.C5.Chats.c5_chat_id.column_key="c5_chat_id"
qsm.C5.Chats.c5_chat_id.column_id="c5_chat_id"
qsm.C5.Chats.c5_chat_id.column_id_numeric = true
qsm.C5.Chats.c5_chat_id.column_name="c5_chat_name"
qsm.C5.Chats.c5_chat_id.column_orderby="c5_chat_id"
qsm.C5.Chats.c5_chat_id.name="Chat ID"
qsm.C5.Chats.c5_chat_id.description="C/5 Chats"
qsm.C5.Chats.c5_chat_id.loc="NF.Form.ChatSpaceID"
qsm.C5.Chats.c5_chat_id.marker="~"
qsm.C5.Chats.c5_chat_id.model="\Numbers\Users\Chats\Model\Chats"
qsm.C5.Chats.c5_chat_id.have_batches = true

qsm.C5.ChatMessages.c5_chatmessage_id.column_key="c5_chatmessage_id"
qsm.C5.ChatMessages.c5_chatmessage_id.column_id="c5_chatmessage_id"
qsm.C5.ChatMessages.c5_chatmessage_id.column_id_numeric = true
qsm.C5.ChatMessages.c5_chatmessage_id.column_name="c5_chatmessage_message"
qsm.C5.ChatMessages.c5_chatmessage_id.column_orderby="c5_chatmessage_id"
qsm.C5.ChatMessages.c5_chatmessage_id.name="Chat Message ID"
qsm.C5.ChatMessages.c5_chatmessage_id.loc="NF.Form.ChatSpaceMessageSpaceID"
qsm.C5.ChatMessages.c5_chatmessage_id.description="C/5 Chat Messages"
qsm.C5.ChatMessages.c5_chatmessage_id.marker="~"
qsm.C5.ChatMessages.c5_chatmessage_id.model="\Numbers\Users\Chats\Model\Chat\Messages"
qsm.C5.ChatMessages.c5_chatmessage_id.have_batches = true
qsm.C5.ChatMessages.c5_chatmessage_id.role = "message"

qsm.C5.ChatGroups.c5_chatgroup_code.column_key="c5_chatgroup_code"
qsm.C5.ChatGroups.c5_chatgroup_code.column_id="c5_chatgroup_code"
qsm.C5.ChatGroups.c5_chatgroup_code.column_id_numeric = false
qsm.C5.ChatGroups.c5_chatgroup_code.column_name="c5_chatgroup_name"
qsm.C5.ChatGroups.c5_chatgroup_code.column_orderby="c5_chatgroup_name"
qsm.C5.ChatGroups.c5_chatgroup_code.name="Chat Group Code"
qsm.C5.ChatGroups.c5_chatgroup_code.loc="NF.Form.ChatGroupCode"
qsm.C5.ChatGroups.c5_chatgroup_code.description="C/5 Chat Groups"
qsm.C5.ChatGroups.c5_chatgroup_code.marker="~"
qsm.C5.ChatGroups.c5_chatgroup_code.model="\Numbers\Users\Chats\Model\Groups"
qsm.C5.ChatGroups.c5_chatgroup_code.have_batches = true
qsm.C5.ChatGroups.c5_chatgroup_code.role = "group"

[development]
