error_reporting = E_WARNING | E_NOTICE | E_ALL | E_STRICT
log_errors = On
display_errors = On

arg_separator.output = "&"

#extension = proctitle.so

date.timezone = America/Toronto

expose_php = Off

magic_quotes_gpc = Off
magic_quotes_runtime = Off
magic_quotes_sybase = Off

memory_limit = 1024M
ignore_user_abort = On
enable_dl = Off
