[module]
module.name = "Numbers\Users\Widgets\Phases"
module.code = "UM-Widget-Phases"
module.title = "Phases Widget"
module.version = "1.0.0"

[dependencies]
dep.submodule.Numbers.Backend.Db.__any = 1
dep.submodule.Numbers.Tenants.Tenants = 1
dep.submodule.Numbers.Users.Users = 1

; --- models (name and parent class) ---
dep.model.\Numbers\Users\Widgets\Phases\Model\Steps = "\Object\Table"

[help]
; Phases Widget
